spring.application.name=apirest-pro-studentdto

# BANNER
spring.banner.charset=UTF-8
spring.banner.location=classpath:my-banner.txt

# DEV: Server port
server.port=8092




# LOGS SETTING
# For all API, DEBUG must be activated in the development stage, never in production 
logging.level.root=INFO

# Only the Service Layer with Warn for example:
#logging.level.com.byschoo.apirest_pro_clientesdto.Service=Warn

# Logs Console Formatted / NO BANNER when active
#logging.structured.format.console=com.byschoo.apirest_pro_clientesdto.Logs.FormatJsonLogger
#logging.structured.format.console=com.byschoo.apirest_pro_clientesdto.Logs.FormatKeyValueLogger

# Logs File Formatted
#logging.structured.format.file=com.byschoo.apirest_pro_clientesdto.Logs.FormatJsonLogger
logging.structured.format.file=com.byschoo.apirest_pro_clientesdto.Logs.FormatKeyValueLogger


# Logs file
logging.file.name=server.log
#logging.level.ch.qos.logback=INFO




# DEV: Finding and reading .env file
spring.config.import=optional:secrets.properties




# DATABASE CONNECTIONS SETTINGS
# DEV: URL TO CONNECT WITH LOCAL POSTGRES (Localhost API)
spring.datasource.url=jdbc:postgresql://localhost:5432/${DEV_DB_NAME}

# DEV: URL TO CONNECT WITH DOCKER CONTAINER POSTGRES (Localhost API) *STOPING LOCAL SERVICE POSTGRES
#spring.datasource.url=jdbc:postgresql://localhost:5433/${DEV_DB_NAME}

# DEV: URL TO CONNECT WITH DOCKER CONTAINER POSTGRES (Docker Container API)
#spring.datasource.url=jdbc:postgresql://my-postgres-container:5433/${DEV_DB_NAME}

# DEV CONNECTION POSTGRES ENCRYTED USER / PASSWORD
#spring.datasource.username=ENC(MbLx55h3pnUL1b2RryjtdLjDUysH2qvk)
#spring.datasource.password=ENC(IEmymN5aZ6dQq8e8+fbKLw==)

# PROD: TO CONNECT WITH HEROKU POSTGRES (Heroku cloud API)
#spring.datasource.url=jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
#spring.datasource.username: ${PROD_DB_USERNAME}
#spring.datasource.password: ${PROD_DB_PASSWORD}


# DATASOURCE VARIABLE CONNECTIONS
spring.datasource.username: ${DEV_DB_USERNAME}
spring.datasource.password: ${DEV_DB_PASSWORD}

# JPA & Hibernate settings
spring.jpa.show-sql=true
# Permite que Hibernate actualice automáticamente el esquema de la base de datos a medida que realizas cambios en tus entidades. No se recomienda para producción, ya que podría haber cambios inesperados en el esquema.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# CONFIG SPRINGDOC OPENAPI SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger.ui.custom.html


# DEV: Jasypt Decrytion configurations FOR RandomSaltGenerator
#jasypt.encryptor.algorithm=PBEWITHMD5ANDTRIPLEDES
#jasypt.encryptor.key-obtention-iterations=1000
#jasypt.encryptor.salt-generator-classname=org.jasypt.salt.RandomSaltGenerator
#jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

# JASYPT AUTOMATIC ENCRYPTION OF PROPERTIES DEC()
# mvn jasypt:encrypt "-Djasypt.encryptor.password=**********" "-Djasypt.encryptor.algorithm=PBEWITHMD5ANDTRIPLEDES"